src/Pubstars2/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PubstarsDtos;
using Pubstars2.Data;
using PubstarsModel;
using Microsoft.AspNetCore.Identity;
using Pubstars2.Models;
using Pubstars2.Models.PubstarsViewModels;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Sakura.AspNetCore;
using Pubstars2.Services;
using Microsoft.AspNetCore.Authorization;

namespace Pubstars2.Controllers
{
    public class GamesController : Controller
    {
        private IPubstarsDb _db;
        private ILeaderboardService _leaderboards;
        private UserManager<ApplicationUser> _userManager;

        public GamesController(IPubstarsDb db, UserManager<ApplicationUser> userManager, ILeaderboardService ls)
        {
            _db = db;
            _userManager = userManager;
            _leaderboards = ls;
        }

        public IActionResult Index(int page)
        {
            List<GameSummaryViewModel> gameSummaries = new List<GameSummaryViewModel>();
            foreach(Game game in _db.Games())
            {                
                gameSummaries.Add(new GameSummaryViewModel(game));
            }
            var viewData = gameSummaries.OrderByDescending(x => x.Time).ToDynamicPagedList(10, page == 0 ? 1 : page);
            return View(viewData);
        }

        [HttpPost]
        [Authorize(Roles = "client")]
        public IActionResult ReportGame([FromBody]RankedGameReport report)
        {
            ProcessGameReport(report);                    
            return Ok(_db.GetUserData());
        }      

        private void ProcessGameReport(RankedGameReport report)
        {
            List<PlayerGameStats> pubplayers = new List<PlayerGameStats>();

            foreach (RankedGameReport.PlayerStatLine p in report.PlayerStats)
            {
                ApplicationUser user = _db.UsersWithPlayer().FirstOrDefault(x => x.UserName == p.Name);
                if (user == null)
                {
                    throw new InvalidOperationException("tried to report game with unregistered players.");
                }

                PlayerGameStats pp = new PlayerGameStats()
                {
                    Player = user.PlayerStats,
                    Team = p.Team == "Red" ? HqmTeam.red : HqmTeam.blue,
                    Goals = p.Goals,
                    Assists = p.Assists,
                    RatingMean = user.PlayerStats.Rating.Mean,
                    RatingStandardDeviation = user.PlayerStats.Rating.StandardDeviation                 
                };                        

                pubplayers.Add(pp);
            }

            Game game = new Game()
            {
                GameId = new Guid(),
                playerStats = pubplayers,
                redScore = report.RedScore,
                blueScore = report.BlueScore,
                date = report.Date
            };
            _db.AddGame(game);

            //apply new ratings
            foreach(KeyValuePair<Player, Rating> kvp in game.GetNewRatings())
            {
                kvp.Key.Rating.Mean = kvp.Value.Mean;
                kvp.Key.Rating.StandardDeviation = kvp.Value.StandardDeviation;
            }
            _db.SaveChanges();
            _leaderboards.FlushLeaderboards();
        }

        public JsonResult GameData()
        {
            List<GameSummaryViewModel> gameSummaries = new List<GameSummaryViewModel>();
            foreach (Game game in _db.Games())
            {
                gameSummaries.Add(new GameSummaryViewModel(game));
            }
            var viewData = gameSummaries.OrderByDescending(x => x.Time);
            return Json(gameSummaries);
        }
  
    }
}

src/Pubstars2/Controllers/LeaderboardController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Pubstars2.Models.PubstarsViewModels;
using Pubstars2.Data;
using System;
using PubstarsModel;
using Pubstars2.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;

namespace Pubstars2.Controllers
{
    public class LeaderboardController : Controller
    {
        ILeaderboardService _leaderboards;

        public LeaderboardController(ILeaderboardService ls)
        {
            _leaderboards = ls;
        }

        public IActionResult Index()
        {           
            return View(_leaderboards.GetLeaderboard());            
        }
    }
}

src/Pubstars2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pubstars2</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-theme.css"></link>
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap-theme.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap-theme.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
                <a asp-area="" asp-controller="Games" asp-action="Index" class="navbar-brand">Games</a>
                <a asp-area="" asp-controller="Leaderboard" asp-action="Index" class="navbar-brand">Leaderboard</a>
            </div>
            <div class="navbar-collapse collapse">                
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>